[package]
name = "il4il-playground"
version = "0.1.0"
description = "IL4IL interactive assembly for WASM"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
il4il_asm = { path = "../il4il_asm" }
wasm-bindgen = "0.2.83"
